update holopin badge
dapr/python-sdk pull request #694
Opened 2024-04-10 12:23 UTC by andriisoldatenko

# Description

The yaml file to award SDK badges had been updated such that each contributor can be awarded with a SDK badge for their contribution to this repo.

## Issue reference

This PR resolves https://github.com/dapr/python-sdk/issues/693 

## Checklist

Please make sure you've completed the relevant tasks for this PR, out of the following list:

* [x] Code compiles correctly
* [x] Created/updated tests
* [x] Extended the documentation

2024-04-23 08:40 UTC, marcduiker requested changes
The alias has some incorrect nested elements. it just needs the 'sdk-badge' value as per suggestion.

2024-04-23 08:40 UTC, marcduiker commented on .github/holopin.yml
> +  alias: { id: clrqfdv4x24910fl5n4iwu5oa, alias: sdk-badge }
```suggestion
  alias: sdk-badge
```

2024-04-30 23:39 UTC, berndverst approved these changes

2024-04-30 23:39 UTC, merged

2024-05-03 10:55 UTC, marcduiker commented
@holopin-bot @andriisoldatenko Thanks for your contribution!