doc: document that users can self-assign issues
dapr/python-sdk pull request #712
Opened 2024-05-14 08:27 UTC by KentHsu

# Description

Refer to [js-sdk](https://github.com/dapr/js-sdk/pull/527), informs users about the GitHub daprbot commands available in the repo with doc link.

## Issue reference

Please reference the issue this PR will close: #602

## Checklist

Please make sure you've completed the relevant tasks for this PR, out of the following list:

* [ ] Code compiles correctly
* [ ] Created/updated tests
* [X] Extended the documentation

2024-05-15 09:39 UTC, elena-kolevska commented
Thanks Kent!
I think we should move the new paragraph at the end of the doc, though, because it doesn't read very well in continuation with the sentence before it ("When contributing to the [Python SDK](https://github.com/dapr/python-sdk) the following rules and best-practices should be followed").

I also think we should add the same paragraph in the `README.md` file, where most developers would probably look first. You can add it after "Generate gRPC Protobuf client" and before "Help & Feedback".

2024-05-16 01:14 UTC, berndverst requested changes

2024-05-16 01:14 UTC, berndverst commented on daprdocs/content/en/python-sdk-contributing/python-contributing.md
> +## Github Dapr Bot Commands
Move to the end of the docs.

2024-05-16 06:48 UTC, KentHsu commented
I movedthe new paragraph to the end of python-contributing.md and decide to add the same paragraph in CONTRIBUTING.md. Please let me know if there are other documentations you want to update.

2024-05-16 06:49 UTC, KentHsu commented on daprdocs/content/en/python-sdk-contributing/python-contributing.md
> +## Github Dapr Bot Commands
Updated

2024-05-16 09:49 UTC, elena-kolevska approved these changes
Looks great! Thanks @KentHsu!

2024-06-24 18:14 UTC, berndverst approved these changes

2024-06-24 18:14 UTC, merged