Implement support cryptography api
dapr/python-sdk pull request #719
Opened 2024-05-24 06:43 UTC by KentHsu

# Description

- Implement below in Dapr gRPC client
    - encrypt/decrypt request iterator and response generator and add tests
    - encrypt/decrypt methods in grpc client and add tests

- Implement below in Dapr gRPC aio client
    - encrypt/decrypt request asynchronous iterator and response asynchronous generator and add tests
    - encrypt/decrypt methods in grpc aio client and add tests

- Add cryptography examples follow [go-sdk crypto example](https://github.com/dapr/go-sdk/pull/492)

## Issue reference

Please reference the issue this PR will close: #548

## Checklist

Please make sure you've completed the relevant tasks for this PR, out of the following list:

* [X] Code compiles correctly
* [X] Created/updated tests
* [X] Extended the documentation

2024-05-31 12:30 UTC, elena-kolevska commented
Thank you very much for the PR Kent, I'll try to get to it asap.

2024-06-24 18:55 UTC, berndverst requested changes
Awesome PR. Thanks @KentHsu 

Can you run `tox -e flake8` and `tox -e ruff` please?

The linter is failing at the moment.

That step runs `tox -e flake8`, `tox -e type`, `tox -e mypy` and `tox -e ruff`.

2024-06-24 23:01 UTC, elena-kolevska requested changes
Great PR @KentHsu, thank you! I have just a few nits.

2024-06-25 19:27 UTC, elena-kolevska commented
This PR should address the linter failing: https://github.com/dapr/python-sdk/pull/725

2024-06-26 17:07 UTC, berndverst commented on examples/crypto/README.md
> +```
Yes please :)

2024-06-27 21:19 UTC, berndverst commented
@KentHsu we are beyond code freeze - are you able to address the comments from @elena-kolevska by end of next week? Otherwise, this is unfortunately going to miss the 1.14 release of the SDK.

2024-06-27 21:20 UTC, berndverst commented
Currently seeing type check failures as well.

I recommend running the above mentioned commands to resolve type check, lint, autoformatting etc

2024-06-28 16:13 UTC, KentHsu commented
Hi @berndverst, @elena-kolevska,
Thank you for reviewing this PR. I just added some commits to address @elena-kolevska's comments.
Please let me know if there's anything you would like to change. Hopefully we can make this PR into the 1.14 release.

2024-06-28 16:15 UTC, KentHsu commented on tests/clients/test_dapr_grpc_request.py
> +        self.assertEqual(req.payload.seq, 0)
I added an empty data test and an larger data test for both encrypt and decrypt request iterators. Async version is also updated.

2024-06-28 16:17 UTC, KentHsu commented on examples/crypto/crypto.py
> +def EncryptDecryptString(dapr: DaprClient):
Fixed!

2024-06-28 16:18 UTC, KentHsu commented on examples/crypto/README.md
> +```
Updated the clean up step to remove these generated files

2024-06-28 20:39 UTC, elena-kolevska approved these changes
Really great work @KentHsu.
I'm approving the PR so as not to block the release, but to make this contribution 100% complete we would need a little example in the [docs](https://docs.dapr.io/developing-applications/sdks/python/python-client/#building-blocks) ([this file](https://github.com/dapr/python-sdk/blob/main/daprdocs/content/en/python-sdk-docs/python-client.md)) so that developers can discover and use your work. 
It would be great if you could send a new PR with that addition.
Thanks again for your contribution, the community appreciates it!

2024-07-02 16:44 UTC, berndverst approved these changes

2024-07-02 16:44 UTC, merged