workflows: update durabletask dependency
dapr/python-sdk pull request #757
Opened 2024-12-03 10:25 UTC by famarting

# Description

Update durabletask dependency to use new dapr fork

Also implements  https://github.com/dapr/python-sdk/issues/711

## Issue reference

We strive to have all PR being opened based on an issue, where the problem or feature have been discussed prior to implementation.

Please reference the issue this PR will close: #_[issue number]_

## Checklist

Please make sure you've completed the relevant tasks for this PR, out of the following list:

* [ ] Code compiles correctly
* [ ] Created/updated tests
* [ ] Extended the documentation

2024-12-03 14:31 UTC, elena-kolevska requested changes
Some comments. Please run `tox -e ruff` and `tox -e flake8` to fix linter errors.

We'll also need to update the grpc library to >= 1.67.0, for compatibility with durabletask.

And finally, we'll need to update the tests in `test_dapr_workflow_context.py` to cover `set-custom_status`.  Something like 
```python
class FakeOrchestrationContext:
    def __init__(self):
        self.instance_id = mock_instance_id
        self.custom_status = None. # <- adding this
    def set_custom_status(self, custom_status):
        self.custom_status = custom_status
        
...

class DaprWorkflowContextTest(unittest.TestCase):
...
def test_workflow_context_functions(self):
...
            dapr_wf_ctx.set_custom_status(mock_status)
            assert fakeContext.custom_status == mock_status            
```

2024-12-03 14:31 UTC, elena-kolevska commented on ext/dapr-ext-workflow/tests/test_workflow_client.py
> +    def purge_workflow(self, instance_id: str, recursive: bool = True):
```suggestion
    def purge_orchestration(self, instance_id: str, recursive: bool = True):
```

2024-12-03 14:31 UTC, elena-kolevska commented on ext/dapr-ext-workflow/dapr/ext/workflow/dapr_workflow_client.py
> +from typing import Any, Optional, TypeVar, Union
```suggestion
from typing import Any, Optional, TypeVar
```

2024-12-04 17:48 UTC, elena-kolevska commented on setup.cfg
> +    grpcio >= 1.67.0
@berndverst any objections on bumping the grpc library version? 
This has been updated in the durable task fork and it's a dependency here.

2024-12-04 18:07 UTC, elena-kolevska submitted a review, later dismissed
LGTM, pending @berndverst 's approval on the grpcio version bump

2025-01-02 13:15 UTC, elena-kolevska commented on setup.cfg
> +    grpcio >= 1.67.0
Version 1.37.0 is very old, it's from April 2021. I think we're safe to update.

2025-01-07 18:17 UTC, berndverst commented on setup.cfg
> +    grpcio >= 1.67.0
This does not mean it would use 1.37 but that 1.37 would be possible to be used. Pip by default will always install the latest version matching the constraint. But if another library a customer is using required `grpcio==1.47.0` for example it would be possible for that specific version to be used.

In Python two versions cannot coexist unlike in other languages. So it's really really important not to force the minimum version to something recent unless this is absolutely necessary.

2025-01-07 18:19 UTC, berndverst commented on dev-requirements.txt
> +durabletask-dapr >= 0.2.0a3
FYI it is a terrible decision that this fork made `grpcio` minimum version as high as it did because it impacts interop with lots of older libraries that pinned older versions. There are plenty of Dapr customers using outdated ML libraries that do this.

2025-01-07 18:38 UTC, elena-kolevska commented on dev-requirements.txt
> +durabletask-dapr >= 0.2.0a3
Since the dapr python sdk is the only user of durabletask-dapr, it's not problematic to reevaluate this decision. @famarting , what do you say?

2025-01-07 18:42 UTC, berndverst requested changes

2025-01-07 18:42 UTC, berndverst commented on setup.cfg
> +    grpcio >= 1.67.0
```suggestion
    grpcio >= 1.42.0
```

Short of auditing the Dapr community to figure out what libraries everyone uses and what the dependencies are pinning... here is a quick thing I identified. This is evidence of at least 1.42.0 being used for something.

https://github.com/tensorflow/tensorflow/blob/8fd1cd0826ef2b12c00540f3acc5a6e3c249f5b2/ci/official/containers/linux_arm64/devel.usertools/test.requirements.txt#L2


If as a project we want to say that we do not care about ML users - or that ML users must be on the latest official `grpcio` packages (highly unlikely because ML package authors are very slow to update packages) then we could consider increasing the minimum version of `grpcio`.

2025-01-08 18:13 UTC, elena-kolevska commented on setup.cfg
> +    grpcio >= 1.67.0
Unfortunately, this version is imposed by the protos used in the [durable task library](https://github.com/microsoft/durabletask-python/blob/main/durabletask/internal/orchestrator_service_pb2_grpc.py#L11).

@cgillum  and @famarting, can we regenerate the protos with an older grpcio version? I suggest we pin it to a version we agree on in the requirements file. I'll check for any CVEs and share here, so we can decide which version would make sense.

2025-01-08 18:17 UTC, berndverst commented on setup.cfg
> +    grpcio >= 1.67.0
Yes let's please do that -- you should not use the latest grpcio-tools to generate the protos -- instead use an older version for wider compatibility with more versions of grpcio.

Is this only an issue in the "fork" or also the upstream version?

2025-01-08 18:18 UTC, elena-kolevska commented on setup.cfg
> +    grpcio >= 1.67.0
It's coming from the upstream, here's the commit: https://github.com/microsoft/durabletask-python/pull/31.

2025-01-09 09:06 UTC, famarting commented on setup.cfg
> +    grpcio >= 1.67.0
if we have to update the protos, I would suggest doing it here https://github.com/dapr/durabletask-protobuf

2025-01-09 12:32 UTC, elena-kolevska commented on setup.cfg
> +    grpcio >= 1.67.0
Here's the PR: https://github.com/dapr/durabletask-python/pull/6
Once that's merged I'll publish a new version and we can update this PR.

2025-01-13 16:57 UTC, elena-kolevska approved these changes

2025-01-14 14:16 UTC, merged